// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// co_occurrence_mat
Rcpp::List co_occurrence_mat(Rcpp::NumericVector idx, Rcpp::NumericVector cl, Rcpp::NumericMatrix same, Rcpp::NumericMatrix count);
RcppExport SEXP corecluster_co_occurrence_mat(SEXP idxSEXP, SEXP clSEXP, SEXP sameSEXP, SEXP countSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cl(clSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type same(sameSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type count(countSEXP);
    __result = Rcpp::wrap(co_occurrence_mat(idx, cl, same, count));
    return __result;
END_RCPP
}
