# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

co_occurrence_mat <- function(idx, cl, same, count) {
    .Call('corecluster_co_occurrence_mat', PACKAGE = 'corecluster', idx, cl, same, count)
}

